
spring:
  redis:
    host: 10.0.191.10
#    host: 192.168.44.147
    port: 6379
    password: amdyes
    timeout: 6000ms
server:
  tomcat:
    uri-encoding: utf-8
  port: 8082

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.cloud.gateway: TRACE
#    org.springframework.boot.autoconfigure: DEBUG
