spring:
  redis:
#    host: 192.168.44.142
    host: 10.0.191.10
    port: 6379
    password: amdyes
    timeout: 6000ms

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.cloud.gateway: TRACE
#    org.springframework.boot.autoconfigure: DEBUG
